### ISSUE TITLE
lsa-es-wiki-2018 is missing

### ISSUE THREAD

**Issue by gmsh** [Lambda-3/indra-composed#14]
lsa-es-wiki-2018 is missing in http://data.lambda3.org/indra/dumps/

**Comment by julsal** [comment]
Hi @gmsh, thanks for your feedback. As I mentioned in issue #15, for a strange reason, the model was not generated. I'll start the generation process now. As soon as it is ready, I let your know.

**Comment by gmsh** [comment]
Thanks for your reply. What about dep-en-wiki-2018 ?

**Comment by julsal** [comment]
lsa-en-wiki-2018 is now available. Please, use the download.sh script to access it.
