### ISSUE TITLE
Can't find lsa 2018 English model

### ISSUE THREAD

**Issue by Dezhi93** [Lambda-3/indra-composed#15]
hi, I can't find lsa-en-wiki-2018 model, where can I get it?
Thank you!

**Comment by julsal** [comment]
Hi @Dezhi93, thanks for your feedback. For a strange reason, the model was not generated. I'll start the generation process now. As soon as it is ready, I let your know.

**Comment by julsal** [comment]
lsa-en-wiki-2018 is now available. Please, use the download.sh script to access it.
