### ISSUE TITLE
Mongo URI

### ISSUE THREAD

**Issue by ghost** [Lambda-3/indra-composed#9]
An exception occurs with this line, with the mongoURI

 - INDRA_JAVA_OPTS=-Xmx4g -Dindra.http.host=0.0.0.0 -Dindra.mongoURI=mongo:27017

in the docker-compose.yml file. Using the format in the previous version seems to work(mongoURI=mongodb://mongo:27017).

**Comment by julsal** [comment]
Hi @srini115, we released a new version which does not depend on mongo anymore. Please, migrate to the new version. In the case you face difficulties, please let us know.
